# 03 | Evaluate independently supplied external manual/predicted labels.
# These 500 rows are provided with predictions. They are NOT generated by
# refitting or applying the internal model, and the published Table 2 may differ.
source("scripts/00_shared.R")
input <- "data/processed/EXTERNAL_VALIDATION.csv"
outdir <- mf_dir("outputs/external_validation")
figdir <- mf_dir("figures/external_validation")
d <- mf_read(input)
mf_check_cols(d, c("City", "Manual_Typology", "Predicted_Typology"), input)
if (anyNA(d[c("City", "Manual_Typology", "Predicted_Typology")])) {
  stop("External validation file contains incomplete required fields.")
}
d$Manual_Typology <- mf_typology_code(d$Manual_Typology, "Manual_Typology")
d$Predicted_Typology <- mf_typology_code(d$Predicted_Typology, "Predicted_Typology")
d$Manual_Typology_Label <- unname(MF_LABELS[d$Manual_Typology])
d$Predicted_Typology_Label <- unname(MF_LABELS[d$Predicted_Typology])
mf_write(d, file.path(outdir, "external_validation_predictions_standardized.csv"))

all <- mf_accuracy_stats(d$Manual_Typology, d$Predicted_Typology)
mf_write(all$metrics, file.path(outdir, "external_validation_overall_metrics.csv"))
mf_write(all$by_class, file.path(outdir, "external_validation_by_class_metrics.csv"))
mf_write(mf_confusion_long(all$confusion),
         file.path(outdir, "external_validation_confusion_matrix_raw.csv"))
by_city <- lapply(split(d, d$City), function(sub) {
  m <- mf_accuracy_stats(sub$Manual_Typology, sub$Predicted_Typology)
  cbind(City = sub$City[1], m$metrics)
})
city_metrics <- do.call(rbind, by_city)
rownames(city_metrics) <- NULL
mf_write(city_metrics, file.path(outdir, "external_validation_city_metrics.csv"))
city_confusions <- lapply(split(d, d$City), function(sub) {
  m <- mf_accuracy_stats(sub$Manual_Typology, sub$Predicted_Typology)
  mf_confusion_long(m$confusion, group = sub$City[1])
})
mf_write(do.call(rbind, city_confusions),
         file.path(outdir, "external_validation_confusion_matrix_by_city.csv"))

# Fixed published Table 2 reference. Differences are logged, never overwritten.
reference <- data.frame(City = c("Cotabato", "Sandakan", "Singapore-Johor Bahru",
                                 "Surabaya", "Vung Tau"),
                        Published_Accuracy = c(0.85, 0.85, 0.86, 0.92, 0.84))
comparison <- merge(reference, city_metrics[, c("City", "N", "Accuracy", "Kappa")],
                    by = "City", all = TRUE)
comparison$Accuracy_Difference <- comparison$Accuracy - comparison$Published_Accuracy
comparison$Matches_Published_To_2dp <- !is.na(comparison$Accuracy_Difference) &
  abs(comparison$Accuracy_Difference) < 0.005
mf_write(comparison, file.path(outdir, "publication_table2_comparison.csv"))
if (!all(comparison$Matches_Published_To_2dp)) {
  warning("Uploaded external validation CSV does not reproduce all values in published Table 2; see comparison CSV.")
}

grDevices::png(file.path(figdir, "external_validation_accuracy_by_city.png"),
              width = 1200, height = 800, res = 150)
par(mar = c(5, 17, 3, 1))
ord <- order(city_metrics$Accuracy)
barplot(city_metrics$Accuracy[ord], names.arg = city_metrics$City[ord],
        horiz = TRUE, xlim = c(0, 1), las = 1, col = "gray45",
        xlab = "Accuracy", main = "External validation by urban area")
grDevices::dev.off()
mf_session(file.path(outdir, "session_info.txt"))
message("03 complete: ", nrow(d), " validation rows; accuracy = ",
        round(all$metrics$Accuracy, 4))
